### ISSUE TITLE
[BUG][COMPAT] Can't Name/Rename/set to Global, Waystone 

### ISSUE THREAD

**Issue by drakray** [Rikshy/AntiqueAtlasExtras#5]
Simple, having Atlas Extra make all placed Waystone use the Random Name, and trying to set to Global or Rename Waystone after placing is not possible.
Removing AtlasExtra fix this.
MC 1.12.2
Forge 2807
Waystones_1.12.2-4.0.67
antiqueatlas-1.12.2-4.5.0
AtlasExtras-1.12.2-1.4
buncha others
https://github.com/blay09/Waystones/issues/158

**Comment by Rikshy** [comment]
Thats wierd.. i am actually just fetching data, not setting any. I will update my waystones reference and test. Thanks!

**Comment by Rikshy** [comment]
Thanks for your report, took me quite some time to figure out that i was overriding the whole implementation of waystones mod :S

now it should be fixed. New version is being reviewed. :)

Thanks again for your report :)

**Comment by drakray** [comment]
Sadly, not fixed :/ (or rather, New bug)
https://pastebin.com/XZjqDB2C
Got this with AtlasExtra 1.5
EDIT: was client connected on a Linux Server, Forge 2811, only Client crashed

**Comment by Rikshy** [comment]
I will try to test it in a bit :)

**Comment by Rikshy** [comment]
Okay so i found the bug (it's a pretty embarrassing one): 
I excecuted server-side code client side. That's why it only crashed on your client, not in my SP test.
Will release a new version when I made a proper test!

**Comment by Rikshy** [comment]
Okay, so my testing was successfull and it should work now!
If there is still something on your mind feel free to open a new issue :)
